version: "3.7"
services: 
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: MyFeedRSS
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - '5432:5432'


  